import React from 'react';
import { Navbar, Card } from './components/Layout';
import { ClipboardCheck, ArrowRight } from 'lucide-react';

const PricingPage = () => {
  return (
    <div className="min-h-screen">
      <Navbar />
      
      <main className="pt-32 pb-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <header className="text-center mb-16">
            <h1 className="text-5xl mb-6">Simple Pricing for <span className="gradient-text">Construction Planning Intelligence</span></h1>
            <p className="text-xl text-slate-400 max-w-2xl mx-auto">
              Start with a quick estimate or generate a detailed professional construction planning report.
            </p>
          </header>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {[
              { 
                name: 'Basic Estimate', 
                price: '₦5,000', 
                priceSub: ' per project',
                desc: 'Ideal for quick early-stage planning.',
                features: ['AI construction cost estimate', 'materials quantity overview', 'construction phase timeline', 'planning insights summary'],
                cta: 'Generate Estimate'
              },
              { 
                name: 'Professional Report', 
                price: '₦25,000', 
                priceSub: ' per project',
                desc: 'Designed for serious project planning.',
                features: ['AI construction cost estimate', 'materials quantity overview', 'construction phase timeline', 'planning insights summary', 'detailed cost breakdown', 'structured materials analysis', 'downloadable professional report', 'project planning documentation'],
                highlighted: true,
                cta: 'Generate Professional Report'
              },
              { 
                name: 'Developer Plan', 
                price: '₦100,000', 
                priceSub: ' per month', 
                desc: 'Designed for builders, architects, and developers who manage multiple projects.',
                features: ['unlimited project estimates', 'unlimited professional reports', 'project dashboard management', 'saved project library', 'priority feature updates'],
                cta: 'Start Developer Plan'
              },
            ].map((p, i) => (
              <Card key={i} className={p.highlighted ? 'border-brand-gold/50 relative overflow-hidden scale-105 z-10' : ''}>
                {p.highlighted && <div className="absolute top-0 right-0 bg-brand-gold text-black text-[10px] font-bold px-3 py-1 rounded-bl-lg uppercase">Most Popular</div>}
                <h3 className="text-2xl mb-2">{p.name}</h3>
                <p className="text-slate-400 text-sm mb-6 h-12">{p.desc}</p>
                <div className="mb-8">
                  <span className="text-4xl font-bold text-white">{p.price}</span>
                  {p.priceSub && <span className="text-slate-400 text-sm">{p.priceSub}</span>}
                </div>
                <ul className="space-y-4 mb-10">
                  {p.features.map((f, j) => (
                    <li key={j} className="flex items-center gap-3 text-sm text-slate-300">
                      <ClipboardCheck className="text-brand-gold w-4 h-4 shrink-0" />
                      <span className="capitalize">{f}</span>
                    </li>
                  ))}
                </ul>
                <button className={p.highlighted ? 'btn-primary w-full flex items-center justify-center gap-2' : 'btn-secondary w-full'}>
                  {p.cta} <ArrowRight className="w-4 h-4" />
                </button>
              </Card>
            ))}
          </div>

          <section className="mt-24">
            <Card className="max-w-4xl mx-auto p-12 bg-black/30 border-white/5">
              <h2 className="text-2xl font-display font-bold mb-6 text-white">Pricing Trust Section</h2>
              <div className="space-y-4 text-slate-400 leading-relaxed">
                <p>
                  All estimates generated by BuildOS Africa are based on structured planning models and available market assumptions.
                </p>
                <p>
                  They are intended to support early-stage planning and feasibility discussions.
                </p>
                <p className="text-sm italic">
                  Final project costs may vary based on design complexity, engineering requirements, and market conditions.
                </p>
              </div>
            </Card>
          </section>
        </div>
      </main>
    </div>
  );
};

export default PricingPage;
